name: "Development CI"

on:
  push:
    branches:
      - v1.x

jobs:
  docker-image-build-publish:
    name: Publish_docker_image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Create .env.local file
        run: |
          touch .env.local
          echo "NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME=${{ secrets.CLOUDINARY_CLOUD_NAME }}" > .env.local
          echo "CLOUDINARY_API_KEY=${{ secrets.CLOUDINARY_API_KEY }}" >> .env.local
          echo "CLOUDINARY_API_SECRET=${{ secrets.CLOUDINARY_API_SECRET }}" >> .env.local
          echo "CLOUDINARY_FOLDER=${{ secrets.CLOUDINARY_FOLDER }}" >> .env.local
          cat .env.local
        shell: bash

      - name: Log in to the azure container registry
        uses: azure/docker-login@v1
        with:
          login-server: amarpetdockerregistry.azurecr.io
          username: ${{ secrets.AZURE_USER }}
          password: ${{ secrets.AZURE_PASSWORD }}

      # - name: Build and push
      #   if: ${{ success() }}
      #   uses: docker/build-push-action@v5
      #   with:
      #     context: .
      #     push: true
      #     tags: amarpetdockerregistry.azurecr.io/blog:latest
