name: "test-workflow-call"

on:
  workflow_call:
    inputs:
      message:
        type: string,
    secrets:
      cloudName:
        required: true
      cloudKey:
        required: true
      cloudSecret:
        required: true

jobs:
  Deploy-docker-image:
    name: Workflow Call
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Print variable
        run: |
          echo ${{ secrets.cloudName }}
          echo ${{ secrets.cloudKey }}
          echo ${{ secrets.cloudSecret }}
          echo ${{ inputs.message }}

        shell: bash
